project:
  type: website
  render:
    - "*.qmd"
    - "!materials/*/exercises/"
  output-dir: docs
  resources:
    - "datasets/*/*.csv"

from: markdown+emoji

website:
  title: "Data Science for Biology Workshop Series"
  page-navigation: true
  navbar:
    background: light
    foreground: dark
    right:
      - text: "Resources"
        href: resources.qmd
      - text: "About"
        href: about.qmd
      - icon: cloud-fill
        href: https://github.com/elsherbini/durban-data-science-for-biology
        aria-label: Posit Cloud
      - icon: github
        href: https://github.com/elsherbini/durban-data-science-for-biology
        aria-label: GitHub
  sidebar:
    - title: "Materials"
      style: docked
      align: left
      contents:
          - section: "Reproducible Data Analysis with R"
            contents:
            - section: "Modules "
              contents:
              - text: "Module 1: Intro to R"
                contents:
                href: materials/1-workshop1/2-intro-to-r/index.qmd
              - text: "Module 2: Welcome to Quarto"
                href: materials/1-workshop1/1-welcome-to-quarto/index.qmd
          - section: "Working with High Dimensional 16S rRNA Sequencing Data in R"
          - section: "Bioinformatics and Transcriptomics Data Analysis"
  page-footer:
    right: "This page is built with {{< fa heart >}} and [Quarto](https://quarto.org/)."
    left: "&copy; 2023. Huge thanks to [Andrew P. Bray](https://github.com/andrewpbray) and [Claus O. Wilke](https://github.com/clauswilke) for open source code."

format: 
  html:
    theme: [default, assets/custom.scss]
    toc: false
    
# Design tips:
# 1. maggieappleton.com
# 2. Palette: https://www.jpl.nasa.gov/images/the-grand-tour-jpl-travel-poster

  