project:
  type: website
  render:
    - "*.qmd"
    - "!materials/*/exercises/"
  output-dir: docs
  resources:
    - "datasets/*/*.csv"

from: markdown+emoji

website:
  title: "Data Science for Biology Workshop Series"
  page-navigation: true
  navbar:
    background: light
    foreground: dark
    right:
      - text: "Glossary"
        href: glossary.html
      - text: "About"
        href: about.qmd
      - icon: cloud-fill
        href: https://github.com/elsherbini/durban-data-science-for-biology
        aria-label: Posit Cloud
      - icon: github
        href: https://github.com/elsherbini/durban-data-science-for-biology
        aria-label: GitHub
  sidebar:
    - title: "Materials"
      style: docked
      align: left
      contents:
          - section: "Reproducible data analysis with R"
            contents:
            - text: "1. Welcome to Quarto"
              href: materials/1-workshop1/1-welcome-to-quarto/index.qmd
  page-footer:
    right: "This page is built with {{< fa heart >}} and [Quarto](https://quarto.org/)."
    left: "&copy; 2023"

format: 
  html:
    theme: [default, assets/custom.scss]
    toc: false
    
# Design tips:
# 1. maggieappleton.com
# 2. Palette: https://www.jpl.nasa.gov/images/the-grand-tour-jpl-travel-poster

  